<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="OpenTK.GLControl" Version="4.0.2" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="levels\two.lvl" />
    <EmbeddedResource Include="levels\three.lvl" />
    <EmbeddedResource Include="levels\four.lvl" />
    <EmbeddedResource Include="shaders\sprite.frag" />
    <EmbeddedResource Include="shaders\particle.frag" />
    <EmbeddedResource Include="shaders\particle.vs" />
    <EmbeddedResource Include="shaders\post_processing.frag" />
    <EmbeddedResource Include="shaders\post_processing.vs" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="shaders\sprite.vs" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="textures\awesomeface.png" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="models\" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="levels\one.lvl" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="textures\background.jpg" />
    <EmbeddedResource Include="textures\block.png" />
    <EmbeddedResource Include="textures\block_solid.png" />
    <EmbeddedResource Include="textures\paddle.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="textures\particle.png" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="textures\powerup_chaos.png" />
    <EmbeddedResource Include="textures\powerup_confuse.png" />
    <EmbeddedResource Include="textures\powerup_increase.png" />
    <EmbeddedResource Include="textures\powerup_passthrough.png" />
    <EmbeddedResource Include="textures\powerup_speed.png" />
    <EmbeddedResource Include="textures\powerup_sticky.png" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>